# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXFpEvp0xK9juRCXh9X9I2ZU1OR4x5eK
"""

import streamlit as st

st.header("sample streamlit application using anaconda prompt")
st.sidebar.write("Sample app")
st.write("My streamlit application")